// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

// Protobuf Java Version: 3.25.1
package com.widedelivery.order.proto;

public interface GetOrderInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.GetOrderInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order_id = 1;</code>
   * @return The orderId.
   */
  String getOrderId();
  /**
   * <code>string order_id = 1;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();
}
