// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.1
package com.widedelivery.order.proto;

public final class OrderOuterClass {
  private OrderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_Order_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_Order_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_OrderResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_OrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_GenericResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_GenericResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013order.proto\022\005order\032\037google/protobuf/ti" +
      "mestamp.proto\"\373\003\n\005Order\022\n\n\002id\030\001 \001(\t\022\017\n\007u" +
      "ser_id\030\002 \001(\t\022\024\n\014cargo_length\030\003 \001(\001\022\023\n\013ca" +
      "rgo_width\030\004 \001(\001\022\024\n\014cargo_height\030\005 \001(\001\022\024\n" +
      "\014cargo_weight\030\006 \001(\001\022\033\n\023departure_longitu" +
      "de\030\007 \001(\t\022\032\n\022departure_latitude\030\010 \001(\t\0222\n\016" +
      "departure_time\030\t \001(\0132\032.google.protobuf.T" +
      "imestamp\022\035\n\025destination_longitude\030\n \001(\t\022" +
      "\034\n\024destination_latitude\030\013 \001(\t\0224\n\020destina" +
      "tion_time\030\014 \001(\0132\032.google.protobuf.Timest" +
      "amp\022\023\n\013description\030\r \001(\t\022\023\n\013need_loader\030" +
      "\016 \001(\010\022\026\n\016payment_method\030\017 \001(\t\022-\n\tcreated" +
      "At\030\020 \001(\0132\032.google.protobuf.Timestamp\022-\n\t" +
      "updatedAt\030\021 \001(\0132\032.google.protobuf.Timest" +
      "amp\",\n\rOrderResponse\022\033\n\005order\030\001 \001(\0132\014.or" +
      "der.Order\"2\n\017GenericResponse\022\016\n\006status\030\001" +
      " \001(\t\022\017\n\007message\030\002 \001(\tB \n\034com.widedeliver" +
      "y.order.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_order_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_order_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_Order_descriptor,
        new String[] { "Id", "UserId", "CargoLength", "CargoWidth", "CargoHeight", "CargoWeight", "DepartureLongitude", "DepartureLatitude", "DepartureTime", "DestinationLongitude", "DestinationLatitude", "DestinationTime", "Description", "NeedLoader", "PaymentMethod", "CreatedAt", "UpdatedAt", });
    internal_static_order_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_order_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_OrderResponse_descriptor,
        new String[] { "Order", });
    internal_static_order_GenericResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_order_GenericResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_GenericResponse_descriptor,
        new String[] { "Status", "Message", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
