// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.1
package com.widedelivery.order.proto;

public interface OrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:order.OrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.order.Order order = 1;</code>
   * @return Whether the order field is set.
   */
  boolean hasOrder();
  /**
   * <code>.order.Order order = 1;</code>
   * @return The order.
   */
  Order getOrder();
  /**
   * <code>.order.Order order = 1;</code>
   */
  OrderOrBuilder getOrderOrBuilder();
}
