// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

// Protobuf Java Version: 3.25.1
package com.widedelivery.order.proto;

/**
 * Protobuf type {@code order.Order}
 */
public final class Order extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:order.Order)
    OrderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Order.newBuilder() to construct.
  private Order(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Order() {
    id_ = "";
    userId_ = "";
    departureLongitude_ = "";
    departureLatitude_ = "";
    destinationLongitude_ = "";
    destinationLatitude_ = "";
    description_ = "";
    paymentMethod_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Order();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return OrderOuterClass.internal_static_order_Order_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return OrderOuterClass.internal_static_order_Order_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Order.class, Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @Override
  public String getId() {
    Object ref = id_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    Object ref = id_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object userId_ = "";
  /**
   * <code>string user_id = 2;</code>
   * @return The userId.
   */
  @Override
  public String getUserId() {
    Object ref = userId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <code>string user_id = 2;</code>
   * @return The bytes for userId.
   */
  @Override
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    Object ref = userId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARGO_LENGTH_FIELD_NUMBER = 3;
  private double cargoLength_ = 0D;
  /**
   * <code>double cargo_length = 3;</code>
   * @return The cargoLength.
   */
  @Override
  public double getCargoLength() {
    return cargoLength_;
  }

  public static final int CARGO_WIDTH_FIELD_NUMBER = 4;
  private double cargoWidth_ = 0D;
  /**
   * <code>double cargo_width = 4;</code>
   * @return The cargoWidth.
   */
  @Override
  public double getCargoWidth() {
    return cargoWidth_;
  }

  public static final int CARGO_HEIGHT_FIELD_NUMBER = 5;
  private double cargoHeight_ = 0D;
  /**
   * <code>double cargo_height = 5;</code>
   * @return The cargoHeight.
   */
  @Override
  public double getCargoHeight() {
    return cargoHeight_;
  }

  public static final int CARGO_WEIGHT_FIELD_NUMBER = 6;
  private double cargoWeight_ = 0D;
  /**
   * <code>double cargo_weight = 6;</code>
   * @return The cargoWeight.
   */
  @Override
  public double getCargoWeight() {
    return cargoWeight_;
  }

  public static final int DEPARTURE_LONGITUDE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile Object departureLongitude_ = "";
  /**
   * <code>string departure_longitude = 7;</code>
   * @return The departureLongitude.
   */
  @Override
  public String getDepartureLongitude() {
    Object ref = departureLongitude_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      departureLongitude_ = s;
      return s;
    }
  }
  /**
   * <code>string departure_longitude = 7;</code>
   * @return The bytes for departureLongitude.
   */
  @Override
  public com.google.protobuf.ByteString
      getDepartureLongitudeBytes() {
    Object ref = departureLongitude_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      departureLongitude_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPARTURE_LATITUDE_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile Object departureLatitude_ = "";
  /**
   * <code>string departure_latitude = 8;</code>
   * @return The departureLatitude.
   */
  @Override
  public String getDepartureLatitude() {
    Object ref = departureLatitude_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      departureLatitude_ = s;
      return s;
    }
  }
  /**
   * <code>string departure_latitude = 8;</code>
   * @return The bytes for departureLatitude.
   */
  @Override
  public com.google.protobuf.ByteString
      getDepartureLatitudeBytes() {
    Object ref = departureLatitude_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      departureLatitude_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPARTURE_TIME_FIELD_NUMBER = 9;
  private com.google.protobuf.Timestamp departureTime_;
  /**
   * <code>.google.protobuf.Timestamp departure_time = 9;</code>
   * @return Whether the departureTime field is set.
   */
  @Override
  public boolean hasDepartureTime() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp departure_time = 9;</code>
   * @return The departureTime.
   */
  @Override
  public com.google.protobuf.Timestamp getDepartureTime() {
    return departureTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : departureTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp departure_time = 9;</code>
   */
  @Override
  public com.google.protobuf.TimestampOrBuilder getDepartureTimeOrBuilder() {
    return departureTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : departureTime_;
  }

  public static final int DESTINATION_LONGITUDE_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile Object destinationLongitude_ = "";
  /**
   * <code>string destination_longitude = 10;</code>
   * @return The destinationLongitude.
   */
  @Override
  public String getDestinationLongitude() {
    Object ref = destinationLongitude_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      destinationLongitude_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_longitude = 10;</code>
   * @return The bytes for destinationLongitude.
   */
  @Override
  public com.google.protobuf.ByteString
      getDestinationLongitudeBytes() {
    Object ref = destinationLongitude_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      destinationLongitude_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_LATITUDE_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile Object destinationLatitude_ = "";
  /**
   * <code>string destination_latitude = 11;</code>
   * @return The destinationLatitude.
   */
  @Override
  public String getDestinationLatitude() {
    Object ref = destinationLatitude_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      destinationLatitude_ = s;
      return s;
    }
  }
  /**
   * <code>string destination_latitude = 11;</code>
   * @return The bytes for destinationLatitude.
   */
  @Override
  public com.google.protobuf.ByteString
      getDestinationLatitudeBytes() {
    Object ref = destinationLatitude_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      destinationLatitude_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATION_TIME_FIELD_NUMBER = 12;
  private com.google.protobuf.Timestamp destinationTime_;
  /**
   * <code>.google.protobuf.Timestamp destination_time = 12;</code>
   * @return Whether the destinationTime field is set.
   */
  @Override
  public boolean hasDestinationTime() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp destination_time = 12;</code>
   * @return The destinationTime.
   */
  @Override
  public com.google.protobuf.Timestamp getDestinationTime() {
    return destinationTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : destinationTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp destination_time = 12;</code>
   */
  @Override
  public com.google.protobuf.TimestampOrBuilder getDestinationTimeOrBuilder() {
    return destinationTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : destinationTime_;
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile Object description_ = "";
  /**
   * <code>string description = 13;</code>
   * @return The description.
   */
  @Override
  public String getDescription() {
    Object ref = description_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 13;</code>
   * @return The bytes for description.
   */
  @Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    Object ref = description_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEED_LOADER_FIELD_NUMBER = 14;
  private boolean needLoader_ = false;
  /**
   * <code>bool need_loader = 14;</code>
   * @return The needLoader.
   */
  @Override
  public boolean getNeedLoader() {
    return needLoader_;
  }

  public static final int PAYMENT_METHOD_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private volatile Object paymentMethod_ = "";
  /**
   * <code>string payment_method = 15;</code>
   * @return The paymentMethod.
   */
  @Override
  public String getPaymentMethod() {
    Object ref = paymentMethod_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      paymentMethod_ = s;
      return s;
    }
  }
  /**
   * <code>string payment_method = 15;</code>
   * @return The bytes for paymentMethod.
   */
  @Override
  public com.google.protobuf.ByteString
      getPaymentMethodBytes() {
    Object ref = paymentMethod_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      paymentMethod_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATEDAT_FIELD_NUMBER = 16;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp createdAt = 16;</code>
   * @return Whether the createdAt field is set.
   */
  @Override
  public boolean hasCreatedAt() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp createdAt = 16;</code>
   * @return The createdAt.
   */
  @Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp createdAt = 16;</code>
   */
  @Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }

  public static final int UPDATEDAT_FIELD_NUMBER = 17;
  private com.google.protobuf.Timestamp updatedAt_;
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 17;</code>
   * @return Whether the updatedAt field is set.
   */
  @Override
  public boolean hasUpdatedAt() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 17;</code>
   * @return The updatedAt.
   */
  @Override
  public com.google.protobuf.Timestamp getUpdatedAt() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp updatedAt = 17;</code>
   */
  @Override
  public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userId_);
    }
    if (Double.doubleToRawLongBits(cargoLength_) != 0) {
      output.writeDouble(3, cargoLength_);
    }
    if (Double.doubleToRawLongBits(cargoWidth_) != 0) {
      output.writeDouble(4, cargoWidth_);
    }
    if (Double.doubleToRawLongBits(cargoHeight_) != 0) {
      output.writeDouble(5, cargoHeight_);
    }
    if (Double.doubleToRawLongBits(cargoWeight_) != 0) {
      output.writeDouble(6, cargoWeight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(departureLongitude_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, departureLongitude_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(departureLatitude_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, departureLatitude_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(9, getDepartureTime());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destinationLongitude_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, destinationLongitude_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destinationLatitude_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, destinationLatitude_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(12, getDestinationTime());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, description_);
    }
    if (needLoader_ != false) {
      output.writeBool(14, needLoader_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(paymentMethod_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, paymentMethod_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(16, getCreatedAt());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(17, getUpdatedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userId_);
    }
    if (Double.doubleToRawLongBits(cargoLength_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, cargoLength_);
    }
    if (Double.doubleToRawLongBits(cargoWidth_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, cargoWidth_);
    }
    if (Double.doubleToRawLongBits(cargoHeight_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, cargoHeight_);
    }
    if (Double.doubleToRawLongBits(cargoWeight_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, cargoWeight_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(departureLongitude_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, departureLongitude_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(departureLatitude_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, departureLatitude_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getDepartureTime());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destinationLongitude_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, destinationLongitude_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destinationLatitude_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, destinationLatitude_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getDestinationTime());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, description_);
    }
    if (needLoader_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, needLoader_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(paymentMethod_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, paymentMethod_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, getCreatedAt());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(17, getUpdatedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Order)) {
      return super.equals(obj);
    }
    Order other = (Order) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getUserId()
        .equals(other.getUserId())) return false;
    if (Double.doubleToLongBits(getCargoLength())
        != Double.doubleToLongBits(
            other.getCargoLength())) return false;
    if (Double.doubleToLongBits(getCargoWidth())
        != Double.doubleToLongBits(
            other.getCargoWidth())) return false;
    if (Double.doubleToLongBits(getCargoHeight())
        != Double.doubleToLongBits(
            other.getCargoHeight())) return false;
    if (Double.doubleToLongBits(getCargoWeight())
        != Double.doubleToLongBits(
            other.getCargoWeight())) return false;
    if (!getDepartureLongitude()
        .equals(other.getDepartureLongitude())) return false;
    if (!getDepartureLatitude()
        .equals(other.getDepartureLatitude())) return false;
    if (hasDepartureTime() != other.hasDepartureTime()) return false;
    if (hasDepartureTime()) {
      if (!getDepartureTime()
          .equals(other.getDepartureTime())) return false;
    }
    if (!getDestinationLongitude()
        .equals(other.getDestinationLongitude())) return false;
    if (!getDestinationLatitude()
        .equals(other.getDestinationLatitude())) return false;
    if (hasDestinationTime() != other.hasDestinationTime()) return false;
    if (hasDestinationTime()) {
      if (!getDestinationTime()
          .equals(other.getDestinationTime())) return false;
    }
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (getNeedLoader()
        != other.getNeedLoader()) return false;
    if (!getPaymentMethod()
        .equals(other.getPaymentMethod())) return false;
    if (hasCreatedAt() != other.hasCreatedAt()) return false;
    if (hasCreatedAt()) {
      if (!getCreatedAt()
          .equals(other.getCreatedAt())) return false;
    }
    if (hasUpdatedAt() != other.hasUpdatedAt()) return false;
    if (hasUpdatedAt()) {
      if (!getUpdatedAt()
          .equals(other.getUpdatedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + CARGO_LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getCargoLength()));
    hash = (37 * hash) + CARGO_WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getCargoWidth()));
    hash = (37 * hash) + CARGO_HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getCargoHeight()));
    hash = (37 * hash) + CARGO_WEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getCargoWeight()));
    hash = (37 * hash) + DEPARTURE_LONGITUDE_FIELD_NUMBER;
    hash = (53 * hash) + getDepartureLongitude().hashCode();
    hash = (37 * hash) + DEPARTURE_LATITUDE_FIELD_NUMBER;
    hash = (53 * hash) + getDepartureLatitude().hashCode();
    if (hasDepartureTime()) {
      hash = (37 * hash) + DEPARTURE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getDepartureTime().hashCode();
    }
    hash = (37 * hash) + DESTINATION_LONGITUDE_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationLongitude().hashCode();
    hash = (37 * hash) + DESTINATION_LATITUDE_FIELD_NUMBER;
    hash = (53 * hash) + getDestinationLatitude().hashCode();
    if (hasDestinationTime()) {
      hash = (37 * hash) + DESTINATION_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getDestinationTime().hashCode();
    }
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + NEED_LOADER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getNeedLoader());
    hash = (37 * hash) + PAYMENT_METHOD_FIELD_NUMBER;
    hash = (53 * hash) + getPaymentMethod().hashCode();
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    if (hasUpdatedAt()) {
      hash = (37 * hash) + UPDATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + getUpdatedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Order parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Order parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Order parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Order parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Order parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Order parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Order parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Order parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Order parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static Order parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Order parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Order parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Order prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code order.Order}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:order.Order)
      OrderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return OrderOuterClass.internal_static_order_Order_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return OrderOuterClass.internal_static_order_Order_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Order.class, Builder.class);
    }

    // Construct using com.widedelivery.order.proto.Order.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDepartureTimeFieldBuilder();
        getDestinationTimeFieldBuilder();
        getCreatedAtFieldBuilder();
        getUpdatedAtFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      userId_ = "";
      cargoLength_ = 0D;
      cargoWidth_ = 0D;
      cargoHeight_ = 0D;
      cargoWeight_ = 0D;
      departureLongitude_ = "";
      departureLatitude_ = "";
      departureTime_ = null;
      if (departureTimeBuilder_ != null) {
        departureTimeBuilder_.dispose();
        departureTimeBuilder_ = null;
      }
      destinationLongitude_ = "";
      destinationLatitude_ = "";
      destinationTime_ = null;
      if (destinationTimeBuilder_ != null) {
        destinationTimeBuilder_.dispose();
        destinationTimeBuilder_ = null;
      }
      description_ = "";
      needLoader_ = false;
      paymentMethod_ = "";
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      updatedAt_ = null;
      if (updatedAtBuilder_ != null) {
        updatedAtBuilder_.dispose();
        updatedAtBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return OrderOuterClass.internal_static_order_Order_descriptor;
    }

    @Override
    public Order getDefaultInstanceForType() {
      return Order.getDefaultInstance();
    }

    @Override
    public Order build() {
      Order result = buildPartial();
      if (!result.isInitialized()) {
        throw Builder.newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Order buildPartial() {
      Order result = new Order(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(Order result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.cargoLength_ = cargoLength_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.cargoWidth_ = cargoWidth_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.cargoHeight_ = cargoHeight_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.cargoWeight_ = cargoWeight_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.departureLongitude_ = departureLongitude_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.departureLatitude_ = departureLatitude_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.departureTime_ = departureTimeBuilder_ == null
            ? departureTime_
            : departureTimeBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.destinationLongitude_ = destinationLongitude_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.destinationLatitude_ = destinationLatitude_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.destinationTime_ = destinationTimeBuilder_ == null
            ? destinationTime_
            : destinationTimeBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.needLoader_ = needLoader_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.paymentMethod_ = paymentMethod_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.createdAt_ = createdAtBuilder_ == null
            ? createdAt_
            : createdAtBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.updatedAt_ = updatedAtBuilder_ == null
            ? updatedAt_
            : updatedAtBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Order) {
        return mergeFrom((Order)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Order other) {
      if (other == Order.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getCargoLength() != 0D) {
        setCargoLength(other.getCargoLength());
      }
      if (other.getCargoWidth() != 0D) {
        setCargoWidth(other.getCargoWidth());
      }
      if (other.getCargoHeight() != 0D) {
        setCargoHeight(other.getCargoHeight());
      }
      if (other.getCargoWeight() != 0D) {
        setCargoWeight(other.getCargoWeight());
      }
      if (!other.getDepartureLongitude().isEmpty()) {
        departureLongitude_ = other.departureLongitude_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getDepartureLatitude().isEmpty()) {
        departureLatitude_ = other.departureLatitude_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.hasDepartureTime()) {
        mergeDepartureTime(other.getDepartureTime());
      }
      if (!other.getDestinationLongitude().isEmpty()) {
        destinationLongitude_ = other.destinationLongitude_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getDestinationLatitude().isEmpty()) {
        destinationLatitude_ = other.destinationLatitude_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (other.hasDestinationTime()) {
        mergeDestinationTime(other.getDestinationTime());
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (other.getNeedLoader() != false) {
        setNeedLoader(other.getNeedLoader());
      }
      if (!other.getPaymentMethod().isEmpty()) {
        paymentMethod_ = other.paymentMethod_;
        bitField0_ |= 0x00004000;
        onChanged();
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      if (other.hasUpdatedAt()) {
        mergeUpdatedAt(other.getUpdatedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              userId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              cargoLength_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              cargoWidth_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              cargoHeight_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 49: {
              cargoWeight_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            case 58: {
              departureLongitude_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              departureLatitude_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  getDepartureTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              destinationLongitude_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              destinationLatitude_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              input.readMessage(
                  getDestinationTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 112: {
              needLoader_ = input.readBool();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            case 122: {
              paymentMethod_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00004000;
              break;
            } // case 122
            case 130: {
              input.readMessage(
                  getCreatedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00008000;
              break;
            } // case 130
            case 138: {
              input.readMessage(
                  getUpdatedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00010000;
              break;
            } // case 138
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public String getId() {
      Object ref = id_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      AbstractMessageLite.checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private Object userId_ = "";
    /**
     * <code>string user_id = 2;</code>
     * @return The userId.
     */
    public String getUserId() {
      Object ref = userId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string user_id = 2;</code>
     * @return The bytes for userId.
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string user_id = 2;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      userId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      userId_ = getDefaultInstance().getUserId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string user_id = 2;</code>
     * @param value The bytes for userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      AbstractMessageLite.checkByteStringIsUtf8(value);
      userId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private double cargoLength_ ;
    /**
     * <code>double cargo_length = 3;</code>
     * @return The cargoLength.
     */
    @Override
    public double getCargoLength() {
      return cargoLength_;
    }
    /**
     * <code>double cargo_length = 3;</code>
     * @param value The cargoLength to set.
     * @return This builder for chaining.
     */
    public Builder setCargoLength(double value) {

      cargoLength_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double cargo_length = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCargoLength() {
      bitField0_ = (bitField0_ & ~0x00000004);
      cargoLength_ = 0D;
      onChanged();
      return this;
    }

    private double cargoWidth_ ;
    /**
     * <code>double cargo_width = 4;</code>
     * @return The cargoWidth.
     */
    @Override
    public double getCargoWidth() {
      return cargoWidth_;
    }
    /**
     * <code>double cargo_width = 4;</code>
     * @param value The cargoWidth to set.
     * @return This builder for chaining.
     */
    public Builder setCargoWidth(double value) {

      cargoWidth_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double cargo_width = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCargoWidth() {
      bitField0_ = (bitField0_ & ~0x00000008);
      cargoWidth_ = 0D;
      onChanged();
      return this;
    }

    private double cargoHeight_ ;
    /**
     * <code>double cargo_height = 5;</code>
     * @return The cargoHeight.
     */
    @Override
    public double getCargoHeight() {
      return cargoHeight_;
    }
    /**
     * <code>double cargo_height = 5;</code>
     * @param value The cargoHeight to set.
     * @return This builder for chaining.
     */
    public Builder setCargoHeight(double value) {

      cargoHeight_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double cargo_height = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCargoHeight() {
      bitField0_ = (bitField0_ & ~0x00000010);
      cargoHeight_ = 0D;
      onChanged();
      return this;
    }

    private double cargoWeight_ ;
    /**
     * <code>double cargo_weight = 6;</code>
     * @return The cargoWeight.
     */
    @Override
    public double getCargoWeight() {
      return cargoWeight_;
    }
    /**
     * <code>double cargo_weight = 6;</code>
     * @param value The cargoWeight to set.
     * @return This builder for chaining.
     */
    public Builder setCargoWeight(double value) {

      cargoWeight_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>double cargo_weight = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCargoWeight() {
      bitField0_ = (bitField0_ & ~0x00000020);
      cargoWeight_ = 0D;
      onChanged();
      return this;
    }

    private Object departureLongitude_ = "";
    /**
     * <code>string departure_longitude = 7;</code>
     * @return The departureLongitude.
     */
    public String getDepartureLongitude() {
      Object ref = departureLongitude_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        departureLongitude_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string departure_longitude = 7;</code>
     * @return The bytes for departureLongitude.
     */
    public com.google.protobuf.ByteString
        getDepartureLongitudeBytes() {
      Object ref = departureLongitude_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        departureLongitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string departure_longitude = 7;</code>
     * @param value The departureLongitude to set.
     * @return This builder for chaining.
     */
    public Builder setDepartureLongitude(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      departureLongitude_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string departure_longitude = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearDepartureLongitude() {
      departureLongitude_ = getDefaultInstance().getDepartureLongitude();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string departure_longitude = 7;</code>
     * @param value The bytes for departureLongitude to set.
     * @return This builder for chaining.
     */
    public Builder setDepartureLongitudeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      AbstractMessageLite.checkByteStringIsUtf8(value);
      departureLongitude_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private Object departureLatitude_ = "";
    /**
     * <code>string departure_latitude = 8;</code>
     * @return The departureLatitude.
     */
    public String getDepartureLatitude() {
      Object ref = departureLatitude_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        departureLatitude_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string departure_latitude = 8;</code>
     * @return The bytes for departureLatitude.
     */
    public com.google.protobuf.ByteString
        getDepartureLatitudeBytes() {
      Object ref = departureLatitude_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        departureLatitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string departure_latitude = 8;</code>
     * @param value The departureLatitude to set.
     * @return This builder for chaining.
     */
    public Builder setDepartureLatitude(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      departureLatitude_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string departure_latitude = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDepartureLatitude() {
      departureLatitude_ = getDefaultInstance().getDepartureLatitude();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string departure_latitude = 8;</code>
     * @param value The bytes for departureLatitude to set.
     * @return This builder for chaining.
     */
    public Builder setDepartureLatitudeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      AbstractMessageLite.checkByteStringIsUtf8(value);
      departureLatitude_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp departureTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> departureTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp departure_time = 9;</code>
     * @return Whether the departureTime field is set.
     */
    public boolean hasDepartureTime() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp departure_time = 9;</code>
     * @return The departureTime.
     */
    public com.google.protobuf.Timestamp getDepartureTime() {
      if (departureTimeBuilder_ == null) {
        return departureTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : departureTime_;
      } else {
        return departureTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp departure_time = 9;</code>
     */
    public Builder setDepartureTime(com.google.protobuf.Timestamp value) {
      if (departureTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        departureTime_ = value;
      } else {
        departureTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp departure_time = 9;</code>
     */
    public Builder setDepartureTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (departureTimeBuilder_ == null) {
        departureTime_ = builderForValue.build();
      } else {
        departureTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp departure_time = 9;</code>
     */
    public Builder mergeDepartureTime(com.google.protobuf.Timestamp value) {
      if (departureTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          departureTime_ != null &&
          departureTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getDepartureTimeBuilder().mergeFrom(value);
        } else {
          departureTime_ = value;
        }
      } else {
        departureTimeBuilder_.mergeFrom(value);
      }
      if (departureTime_ != null) {
        bitField0_ |= 0x00000100;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp departure_time = 9;</code>
     */
    public Builder clearDepartureTime() {
      bitField0_ = (bitField0_ & ~0x00000100);
      departureTime_ = null;
      if (departureTimeBuilder_ != null) {
        departureTimeBuilder_.dispose();
        departureTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp departure_time = 9;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDepartureTimeBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return getDepartureTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp departure_time = 9;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDepartureTimeOrBuilder() {
      if (departureTimeBuilder_ != null) {
        return departureTimeBuilder_.getMessageOrBuilder();
      } else {
        return departureTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : departureTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp departure_time = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
        getDepartureTimeFieldBuilder() {
      if (departureTimeBuilder_ == null) {
        departureTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDepartureTime(),
                getParentForChildren(),
                isClean());
        departureTime_ = null;
      }
      return departureTimeBuilder_;
    }

    private Object destinationLongitude_ = "";
    /**
     * <code>string destination_longitude = 10;</code>
     * @return The destinationLongitude.
     */
    public String getDestinationLongitude() {
      Object ref = destinationLongitude_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        destinationLongitude_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string destination_longitude = 10;</code>
     * @return The bytes for destinationLongitude.
     */
    public com.google.protobuf.ByteString
        getDestinationLongitudeBytes() {
      Object ref = destinationLongitude_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        destinationLongitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_longitude = 10;</code>
     * @param value The destinationLongitude to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationLongitude(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      destinationLongitude_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_longitude = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestinationLongitude() {
      destinationLongitude_ = getDefaultInstance().getDestinationLongitude();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string destination_longitude = 10;</code>
     * @param value The bytes for destinationLongitude to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationLongitudeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      AbstractMessageLite.checkByteStringIsUtf8(value);
      destinationLongitude_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private Object destinationLatitude_ = "";
    /**
     * <code>string destination_latitude = 11;</code>
     * @return The destinationLatitude.
     */
    public String getDestinationLatitude() {
      Object ref = destinationLatitude_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        destinationLatitude_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string destination_latitude = 11;</code>
     * @return The bytes for destinationLatitude.
     */
    public com.google.protobuf.ByteString
        getDestinationLatitudeBytes() {
      Object ref = destinationLatitude_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        destinationLatitude_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string destination_latitude = 11;</code>
     * @param value The destinationLatitude to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationLatitude(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      destinationLatitude_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string destination_latitude = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearDestinationLatitude() {
      destinationLatitude_ = getDefaultInstance().getDestinationLatitude();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string destination_latitude = 11;</code>
     * @param value The bytes for destinationLatitude to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationLatitudeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      AbstractMessageLite.checkByteStringIsUtf8(value);
      destinationLatitude_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp destinationTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> destinationTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp destination_time = 12;</code>
     * @return Whether the destinationTime field is set.
     */
    public boolean hasDestinationTime() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp destination_time = 12;</code>
     * @return The destinationTime.
     */
    public com.google.protobuf.Timestamp getDestinationTime() {
      if (destinationTimeBuilder_ == null) {
        return destinationTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : destinationTime_;
      } else {
        return destinationTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp destination_time = 12;</code>
     */
    public Builder setDestinationTime(com.google.protobuf.Timestamp value) {
      if (destinationTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        destinationTime_ = value;
      } else {
        destinationTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp destination_time = 12;</code>
     */
    public Builder setDestinationTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (destinationTimeBuilder_ == null) {
        destinationTime_ = builderForValue.build();
      } else {
        destinationTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp destination_time = 12;</code>
     */
    public Builder mergeDestinationTime(com.google.protobuf.Timestamp value) {
      if (destinationTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000800) != 0) &&
          destinationTime_ != null &&
          destinationTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getDestinationTimeBuilder().mergeFrom(value);
        } else {
          destinationTime_ = value;
        }
      } else {
        destinationTimeBuilder_.mergeFrom(value);
      }
      if (destinationTime_ != null) {
        bitField0_ |= 0x00000800;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp destination_time = 12;</code>
     */
    public Builder clearDestinationTime() {
      bitField0_ = (bitField0_ & ~0x00000800);
      destinationTime_ = null;
      if (destinationTimeBuilder_ != null) {
        destinationTimeBuilder_.dispose();
        destinationTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp destination_time = 12;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDestinationTimeBuilder() {
      bitField0_ |= 0x00000800;
      onChanged();
      return getDestinationTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp destination_time = 12;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDestinationTimeOrBuilder() {
      if (destinationTimeBuilder_ != null) {
        return destinationTimeBuilder_.getMessageOrBuilder();
      } else {
        return destinationTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : destinationTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp destination_time = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
        getDestinationTimeFieldBuilder() {
      if (destinationTimeBuilder_ == null) {
        destinationTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDestinationTime(),
                getParentForChildren(),
                isClean());
        destinationTime_ = null;
      }
      return destinationTimeBuilder_;
    }

    private Object description_ = "";
    /**
     * <code>string description = 13;</code>
     * @return The description.
     */
    public String getDescription() {
      Object ref = description_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string description = 13;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 13;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 13;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      AbstractMessageLite.checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private boolean needLoader_ ;
    /**
     * <code>bool need_loader = 14;</code>
     * @return The needLoader.
     */
    @Override
    public boolean getNeedLoader() {
      return needLoader_;
    }
    /**
     * <code>bool need_loader = 14;</code>
     * @param value The needLoader to set.
     * @return This builder for chaining.
     */
    public Builder setNeedLoader(boolean value) {

      needLoader_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>bool need_loader = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearNeedLoader() {
      bitField0_ = (bitField0_ & ~0x00002000);
      needLoader_ = false;
      onChanged();
      return this;
    }

    private Object paymentMethod_ = "";
    /**
     * <code>string payment_method = 15;</code>
     * @return The paymentMethod.
     */
    public String getPaymentMethod() {
      Object ref = paymentMethod_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        paymentMethod_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string payment_method = 15;</code>
     * @return The bytes for paymentMethod.
     */
    public com.google.protobuf.ByteString
        getPaymentMethodBytes() {
      Object ref = paymentMethod_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        paymentMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string payment_method = 15;</code>
     * @param value The paymentMethod to set.
     * @return This builder for chaining.
     */
    public Builder setPaymentMethod(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      paymentMethod_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>string payment_method = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaymentMethod() {
      paymentMethod_ = getDefaultInstance().getPaymentMethod();
      bitField0_ = (bitField0_ & ~0x00004000);
      onChanged();
      return this;
    }
    /**
     * <code>string payment_method = 15;</code>
     * @param value The bytes for paymentMethod to set.
     * @return This builder for chaining.
     */
    public Builder setPaymentMethodBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      AbstractMessageLite.checkByteStringIsUtf8(value);
      paymentMethod_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp createdAt = 16;</code>
     * @return Whether the createdAt field is set.
     */
    public boolean hasCreatedAt() {
      return ((bitField0_ & 0x00008000) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 16;</code>
     * @return The createdAt.
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 16;</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
      } else {
        createdAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 16;</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 16;</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (((bitField0_ & 0x00008000) != 0) &&
          createdAt_ != null &&
          createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedAtBuilder().mergeFrom(value);
        } else {
          createdAt_ = value;
        }
      } else {
        createdAtBuilder_.mergeFrom(value);
      }
      if (createdAt_ != null) {
        bitField0_ |= 0x00008000;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 16;</code>
     */
    public Builder clearCreatedAt() {
      bitField0_ = (bitField0_ & ~0x00008000);
      createdAt_ = null;
      if (createdAtBuilder_ != null) {
        createdAtBuilder_.dispose();
        createdAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 16;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      bitField0_ |= 0x00008000;
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 16;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 16;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private com.google.protobuf.Timestamp updatedAt_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp updatedAt = 17;</code>
     * @return Whether the updatedAt field is set.
     */
    public boolean hasUpdatedAt() {
      return ((bitField0_ & 0x00010000) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp updatedAt = 17;</code>
     * @return The updatedAt.
     */
    public com.google.protobuf.Timestamp getUpdatedAt() {
      if (updatedAtBuilder_ == null) {
        return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      } else {
        return updatedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updatedAt = 17;</code>
     */
    public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updatedAt_ = value;
      } else {
        updatedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updatedAt = 17;</code>
     */
    public Builder setUpdatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (updatedAtBuilder_ == null) {
        updatedAt_ = builderForValue.build();
      } else {
        updatedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updatedAt = 17;</code>
     */
    public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
      if (updatedAtBuilder_ == null) {
        if (((bitField0_ & 0x00010000) != 0) &&
          updatedAt_ != null &&
          updatedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getUpdatedAtBuilder().mergeFrom(value);
        } else {
          updatedAt_ = value;
        }
      } else {
        updatedAtBuilder_.mergeFrom(value);
      }
      if (updatedAt_ != null) {
        bitField0_ |= 0x00010000;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updatedAt = 17;</code>
     */
    public Builder clearUpdatedAt() {
      bitField0_ = (bitField0_ & ~0x00010000);
      updatedAt_ = null;
      if (updatedAtBuilder_ != null) {
        updatedAtBuilder_.dispose();
        updatedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updatedAt = 17;</code>
     */
    public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
      bitField0_ |= 0x00010000;
      onChanged();
      return getUpdatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp updatedAt = 17;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      if (updatedAtBuilder_ != null) {
        return updatedAtBuilder_.getMessageOrBuilder();
      } else {
        return updatedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp updatedAt = 17;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
        getUpdatedAtFieldBuilder() {
      if (updatedAtBuilder_ == null) {
        updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getUpdatedAt(),
                getParentForChildren(),
                isClean());
        updatedAt_ = null;
      }
      return updatedAtBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:order.Order)
  }

  // @@protoc_insertion_point(class_scope:order.Order)
  private static final Order DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Order();
  }

  public static Order getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Order>
      PARSER = new com.google.protobuf.AbstractParser<Order>() {
    @Override
    public Order parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Order> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Order> getParserForType() {
    return PARSER;
  }

  @Override
  public Order getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

