// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

// Protobuf Java Version: 3.25.1
package com.widedelivery.order.proto;

public final class OrderProto {
  private OrderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_GetOrderInput_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_GetOrderInput_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016services.proto\022\005order\032\026rpc_create_orde" +
      "r.proto\032\nuser.proto\032\013order.proto\"!\n\rGetO" +
      "rderInput\022\020\n\010order_id\030\001 \001(\t2\216\001\n\014OrderSer" +
      "vice\022D\n\013CreateOrder\022\027.order.CreateOrderI" +
      "nput\032\032.order.CreateOrderResponse\"\000\0228\n\010Ge" +
      "tOrder\022\024.order.GetOrderInput\032\024.order.Ord" +
      "erResponse\"\000B,\n\034com.widedelivery.order.p" +
      "rotoB\nOrderProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          RpcCreateOrder.getDescriptor(),
          User.getDescriptor(),
          OrderOuterClass.getDescriptor(),
        });
    internal_static_order_GetOrderInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_order_GetOrderInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_GetOrderInput_descriptor,
        new String[] { "OrderId", });
    RpcCreateOrder.getDescriptor();
    User.getDescriptor();
    OrderOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
