// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_create_order.proto

// Protobuf Java Version: 3.25.1
package com.widedelivery.order.proto;

public final class RpcCreateOrder {
  private RpcCreateOrder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_CreateOrderInput_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_CreateOrderInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_order_CreateOrderResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_order_CreateOrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026rpc_create_order.proto\022\005order\032\037google/" +
      "protobuf/timestamp.proto\032\013order.proto\032\nu" +
      "ser.proto\"\275\003\n\020CreateOrderInput\022\034\n\004user\030\001" +
      " \001(\0132\016.order.UserDTO\022\022\n\ncargo_type\030\002 \001(\t" +
      "\022\024\n\014cargo_length\030\003 \001(\001\022\023\n\013cargo_width\030\004 " +
      "\001(\001\022\024\n\014cargo_height\030\005 \001(\001\022\024\n\014cargo_weigh" +
      "t\030\006 \001(\001\022\033\n\023departure_longitude\030\007 \001(\t\022\032\n\022" +
      "departure_latitude\030\010 \001(\t\0222\n\016departure_ti" +
      "me\030\t \001(\0132\032.google.protobuf.Timestamp\022\035\n\025" +
      "destination_longitude\030\n \001(\t\022\034\n\024destinati" +
      "on_latitude\030\013 \001(\t\0224\n\020destination_time\030\014 " +
      "\001(\0132\032.google.protobuf.Timestamp\022\023\n\013descr" +
      "iption\030\r \001(\t\022\023\n\013need_loader\030\016 \001(\010\022\026\n\016pay" +
      "ment_method\030\017 \001(\t\"2\n\023CreateOrderResponse" +
      "\022\033\n\005order\030\001 \001(\0132\014.order.OrderB \n\034com.wid" +
      "edelivery.order.protoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          OrderOuterClass.getDescriptor(),
          User.getDescriptor(),
        });
    internal_static_order_CreateOrderInput_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_order_CreateOrderInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_CreateOrderInput_descriptor,
        new String[] { "User", "CargoType", "CargoLength", "CargoWidth", "CargoHeight", "CargoWeight", "DepartureLongitude", "DepartureLatitude", "DepartureTime", "DestinationLongitude", "DestinationLatitude", "DestinationTime", "Description", "NeedLoader", "PaymentMethod", });
    internal_static_order_CreateOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_order_CreateOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_order_CreateOrderResponse_descriptor,
        new String[] { "Order", });
    com.google.protobuf.TimestampProto.getDescriptor();
    OrderOuterClass.getDescriptor();
    User.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
